version: "2"
services:
  server:
    build: .
    ports:
    - "5000:5000"
    depends_on:
    - mongo
    command:
      node server.js
  mongo:
    image: mongo
    ports:
    - "27018:27017"
  test:
    build: .
    volumes:
      - ./test:/test
    ports:
      - 5000:5000
    command:
      npm test